# -*- coffee -*- -p
author: 'YC <yinso.chen@gmail.com>'
name: 'checklet'
description: 'A simple validation framework'
version: '0.1.0'
repository:
  type: 'git'
  url: 'git://github.com/yinso/pagelet.git'
main: './lib/'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
dependencies:
  yargs: =1.3.3
  underscore: =1.7.0
  funclet: '>=0.1.0'
  errorlet: '>=0.1.0'
  loglet: '>=0.1.1'
  # for validator
  email-validator: =1.0.1
devDependencies:
  coffee-script: =1.8.0
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.3.0'
  pegjs: =0.8.0
